FROM debian:bookworm-slim
ARG version_branch
ARG version_hash
ARG build_datetime
ENV VERSION_BRANCH=${version_branch}
ENV VERSION_HASH=${version_hash}
ENV BUILD_DATETIME=${build_datetime}
RUN apt-get update && apt-get install -y ca-certificates curl && rm -rf /var/lib/apt/lists/*
COPY ./bin/traxcli /usr/local/bin/traxcli
CMD ["/usr/local/bin/traxcli"]
