FROM debian:bookworm-slim
ARG version_branch
ARG version_hash
ARG build_datetime
ENV VERSION_BRANCH=${version_branch}
ENV VERSION_HASH=${version_hash}
ENV BUILD_DATETIME=${build_datetime}
RUN apt-get update && apt-get install -y ca-certificates curl && rm -rf /var/lib/apt/lists/*
COPY ./bin/traxctrl /usr/local/bin/traxctrl
COPY ./bin/traxcoord /usr/local/bin/traxcoord
CMD ["/usr/local/bin/traxctrl"]
